[package]
name = "idkit-c-swift-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idkit = { git = "https://github.com/kroist/idkit-rs.git" }
